// <auto-generated />
using System;
using Erm.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erm.DataAccess.Migrations
{
    [DbContext(typeof(ErmDbContext))]
    partial class ErmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erm.DataAccess.Models.BusinessProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("business_process", (string)null);
                });

            modelBuilder.Entity("Erm.DataAccess.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessProcessId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("business_process_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("message");

                    b.Property<int?>("RiskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_id");

                    b.Property<int?>("RiskProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.HasIndex("RiskId");

                    b.HasIndex("RiskProfileId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Erm.DataAccess.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("name");

                    b.Property<int>("RiskProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("risk_profile_id");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_frame");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RiskProfileId");

                    b.ToTable("risk", (string)null);
                });

            modelBuilder.Entity("Erm.DataAccess.Models.RiskProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("business_process_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description");

                    b.Property<int>("OccurrenceProbability")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurrence_probability");

                    b.Property<int>("PotentialBusinessImpact")
                        .HasColumnType("INTEGER")
                        .HasColumnName("potential_business_impact");

                    b.Property<string>("PotentialSolution")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("potential_solution");

                    b.Property<string>("RiskName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("risk_name");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.HasIndex("RiskName")
                        .IsUnique();

                    b.ToTable("risk_profile", (string)null);
                });

            modelBuilder.Entity("Erm.DataAccess.Models.Notification", b =>
                {
                    b.HasOne("Erm.DataAccess.Models.BusinessProcess", "BusinessProcess")
                        .WithMany("Notifications")
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erm.DataAccess.Models.Risk", "Risk")
                        .WithMany("Notifications")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erm.DataAccess.Models.RiskProfile", "RiskProfile")
                        .WithMany("Notifications")
                        .HasForeignKey("RiskProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProcess");

                    b.Navigation("Risk");

                    b.Navigation("RiskProfile");
                });

            modelBuilder.Entity("Erm.DataAccess.Models.Risk", b =>
                {
                    b.HasOne("Erm.DataAccess.Models.RiskProfile", "RiskProfiles")
                        .WithMany("Risks")
                        .HasForeignKey("RiskProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskProfiles");
                });

            modelBuilder.Entity("Erm.DataAccess.Models.RiskProfile", b =>
                {
                    b.HasOne("Erm.DataAccess.Models.BusinessProcess", "BusinessProcess")
                        .WithMany("RiskProfiles")
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("Erm.DataAccess.Models.BusinessProcess", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RiskProfiles");
                });

            modelBuilder.Entity("Erm.DataAccess.Models.Risk", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Erm.DataAccess.Models.RiskProfile", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
